[build-system]
requires = ["setuptools==68.0.0", "wheel==0.40.0"]
build-backend = "setuptools.build_meta"

[project]
name = "atticus-demo"
version = "2.2"
description = "Atticus Options Trading Platform"
requires-python = ">=3.9,<3.10" 