services:
  - type: web
    name: atticus-demo
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -m backend.main
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: PYTHONPATH
        value: /opt/render/project/src 