services:
  - type: web
    name: atticus-demo
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn backend.api:app --host 0.0.0.0 --port $PORT --ws-ping-interval 20 --ws-ping-timeout 20
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: ATTICUS_DEMO_MODE
        value: "true"
      - key: ATTICUS_CORS_ORIGINS
        value: "https://preview--atticus-option-flow.lovable.app,https://atticus-option-flow.lovable.app,https://atticus-demo.onrender.com,https://atticustrade.com,https://preview--turbo-options-platform.lovable.app"
      - key: ATTICUS_WS_PING_INTERVAL
        value: "20"
      - key: ATTICUS_WS_PING_TIMEOUT
        value: "20"
      - key: VITE_API_URL
        value: "https://atticus-demo.onrender.com"
      - key: VITE_WS_URL
        value: "wss://atticus-demo.onrender.com/ws" 