services:
  - type: web
    name: atticus-demo
    env: python
    buildCommand: |
      python3.11 -m venv .venv
      source .venv/bin/activate
      python -m pip install --upgrade pip==24.3.1
      pip install setuptools==68.0.0 wheel==0.40.0
      pip install -r requirements.txt
    startCommand: uvicorn backend.api:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: VIRTUAL_ENV
        value: /opt/render/project/src/.venv 